#!/usr/bin/env python
import struct
import sys
import subprocess

def shellquote(s):
    return "'" + s.replace("'", "'\\''") + "'"

real = open(sys.argv[1], 'rb')

dll = open(sys.argv[2], 'r+b')
dll.seek(0x108)
_, _, _, _, _, cFuncs, cNames, rvaFuncs, rvaNames, rvaNameOrdinals = struct.unpack('<IIIIIIIIII', dll.read(40))

names = {}
for x in xrange(cNames):
    dll.seek(rvaNames + x * 4)
    rva = struct.unpack('<I', dll.read(4))[0]
    dll.seek(rva)
    s = ''
    while True:
        c = dll.read(1)
        if c == '\x00':
            break
        s += c
    names[s] = x
    names['__wine_stub_' + s] = x

for line in subprocess.check_output('nm ' + shellquote(sys.argv[1]) + ' | grep " [tT] "', shell=True).splitlines():
    addr, _, name = line.strip().split(' ')
    if name in names:
        addr = int(addr, 16)
        x = names[name]
        dll.seek(rvaFuncs + x * 4)
        rva = struct.unpack('<I', dll.read(4))[0]
        dll.seek(rva)
        real.seek(addr - 0x7bc00000)
        if real.read(4) == '\x55\x48\x89\xe5':
            dll.write('\x55\x48\x89\xe5\xc9\x68' + struct.pack('<I', addr) + '\xc3')
        else:
            if '__wine_stub_' not in name:
                print name
            dll.write('\x68' + struct.pack('<I', addr) + '\xc3')
